### ISSUE TITLE
database.php not found

### ISSUE THREAD

**Issue by tuannvbg** [alexaverill/Quiz#9]
in file header.php write:
include('templates/head.php');
include('database.php');
source code not include database.php

**Comment by AbdullahNauman** [comment]
You seem to be correct.The  'database.php' file is not available in locally for the header, which seems to be transmitting an **E_WARNING.**

**Comment by alexaverill** [comment]
database.php should be a php file that contains the following information:
    $data_username = "'username'";        //Database User
    $data_password = "password";        //Database Password
    $data_host = "localhost";   //Database Host localhost should work as defualt
    $name_database = "databasename";        //Database Name*/
